<style type="text/css">
	#wrapMain{margin-left:0px;}
</style>
<script type="text/javascript">
	var main_channelLib = [
		{docLibID:"<c:out value="${channelLib0.docLibID}"/>", fvID:"<c:out value="${channelLib0.folderID}"/>"},
		{docLibID:"<c:out value="${channelLib1.docLibID}"/>", fvID:"<c:out value="${channelLib1.folderID}"/>"}
	]
</script>
<script type="text/javascript" src=""></script>
