
<style type="text/css">
	#wrapMain{margin-left:0px; padding: 0;}
	.selfTab{width:70px;cursor:pointer;padding:3px;}
	#searchList,#queryReset{
		background: none;
		margin-top:5px;
		border: none;
	}

	.detail_employee a:focus,.detail_employee a:visited,.detail_employee a:active,.detail_employee a:hover{
		text-decoration: none;
	}

	#exp_detail ._sel,#exp_detail_app ._sel{
		float:left;
		margin:10px 0px 10px 10px;
	}
	._sel .col_sel{
		float:left;
    	width:185px;
	}
	._sel .sel_Id{
		float:left;
    	width:150px;
	}
	._sel .emp_sel{
		float:left;
    	width:240px;
	}
	._sel .src_sel{
		float:left;
    	width:240px;
	}
	._sel .editor_sel{
		float:left;
    	width:240px;
	}
	._sel .articleSelect{
		float:left;
    	width:160px;
	}
	._sel .checkbox_ahthor{
		float:left;
    	width:65px;
	}

	#exp_employeeTab .input_select,#exp_detail .input_selectId,#exp_employeeTab_app .input_select,
	#exp_detail_app .input_selectId{
	    border: 1px solid #ddd;
	    height: 26px;
	    line-height: 26px;
	    padding-left: 5px;
	    color: #333;
	    width: 115px;
	    margin: 0 5px;
		border-radius: 0;
		background:none;
	}
	
	.publishTime{
		color:#666;
    	font-size:13px;
	}
	.publishTime1{
		float:left;
		color:#666;
    	font-size:13px;
    	height:24px;
    	line-height: 24px;
    	margin-right: 5px;
	}
	.articleSelect #exp_articleSelect{
		float:left;
		width:90px;
	    margin-bottom: 0;
	    height: 24px;
	    padding: 0;
	    border-radius: 0;
	    border: 1px solid #A9A9A9;
	    box-shadow: none;
	    cursor: inherit; 
	}
	.articleSelect #exp_articleSelect_app{
		float:left;
		width:90px;
	    margin-bottom: 0;
	    height: 24px;
	    padding: 0;
	    border-radius: 0;
	    border: 1px solid #A9A9A9;
	    box-shadow: none;
	    cursor: inherit; 
	}
    #exp_detail .see,#exp_detail_app .see{
		background: #1bb8fa;
	    color: #fff;
	    border-radius: 3px;
	    border: none;
	    width: 67px;
	    height: 26px;
	}
	
	.detail_employee .lookBtn,.detail_employee .resetBtn{
	   margin-top: -10px;
	}
	.ml6{
		margin-left: 6px;
	}
	#exp_chTimeRegionDept .pubtimeTime,#exp_chTimeRegionDept_app .pubtimeTime{
		border: 1px solid #ddd;
	    height: 26px;
	    font-size: 12px;
	    padding-left: 5px;
	    border-radius: 0;
    	background: #fff;
    	width: 132px;
	}
	.publishTime {
	    color: #666;
	    font-size: 13px;
	    float: left;
	    line-height: 23px;
	}
	#divQueryCust .detail_employee{
	    float:left;
	}
	#divQueryCust_app .detail_employee{
	    float:left;
		clear: both;
	    width:1100px;
	}
	#divQueryCust .detail_employee .times{
	    float:left;
	    clear:both;
	    margin-top: 10px;
	}
	.status{
		border-left: 0;
    	border-right: 0;
    	padding: 10px;
	}
	#doclistframe{
		margin-left: 10px;
	}
	.channels{
		margin-left: 10px;
	}
	#divQueryCust_app .detail_employee .times{
	    float:left;
	    clear:both;
	    margin-top: 6px;
	    margin-left:9px;
	}
	#exp_chTimeRegionDept .time_stat,#exp_chTimeRegionDept_app .time_stat{
	    width: 70px;
	    display: inline-block;
	    text-align: center;
	    color: #333;
	    font-size: 13px;
	    float: left;
	    margin-left: 10px;
	    height: 26px;
	    line-height: 26px;
	    border: 1px solid #ddd;
	    border-radius: 3px;
	}
	.detail_employee .times{
	    float:left;
	    clear:both;
	    margin-top: 10px;
   }
   .page-unselected, .page-selected{
   		height: 22px;
   }
   [class^="icon-"], [class*=" icon-"]{
   		margin-top: 3px;
   }
   #exp_employeeTab .exportBtn{
   		border-radius: 3px;
	    color: #fff;
	    background: #00a0e6;
	    width:93px;
	    height:30px;
	    margin-left:10px;
	    font-size: 13px;
	    cursor: pointer;
	    border: none;
   }
   #exp_employeeTab_app{
        display:none;
   }
   #exp_employeeTab_app .exportBtn{
   		border-radius: 3px;
	    color: #fff;
	    background: #00a0e6;
	    width:93px;
	    height:30px;
	    margin-left:10px;
	    font-size: 13px;
	    cursor: pointer;
	    border: none;
   }
   #exp_detail .input_selectId{
		width: 120px;
   }
   .select_time{
      font-size: 13px;
	  BACKGROUND: #1bb8fa;
	  COLOR: #fff !important;
	  border: none !important;
   }

   .modal .modal-body{
        height: 340px;
    }
   .clearfix:after {
        content: ".";
        display: block;
        clear: both;
        visibility:hidden;
        line-height: 0;
        height: 0;
        font-size:0;
   }
   .fl{
        float: left;
   }
   .department-search{
       margin-left: 160px;
   }
   .department-search input{
       width: 220px;
       height: 30px;
       padding: 0 4px;
       line-height: 30px;
       font-size: 14px;
       font-weight: normal;
       border: 1px solid #ddd;
   }
   .department-search ul{
       border: 1px solid #ddd;
       border-top: none;
       max-height: 280px;
       overflow: auto;
   }
   .department-search ul li{
       height: 30px;
       line-height: 30px;
       text-align: left;
       border-bottom: 1px solid #ddd;
       padding: 4px 0 4px 10px;
       cursor: pointer;
       font-size: 14px;
       font-weight: normal;
       background: none;
   }
   .department-search ul li:nth-last-child(1){
       border-bottom: none;
   }
   .department-search ul li:hover{
       background: lightcyan;
   }
   .modal-body>div{
       position: relative;
   }
   .search-btn{
       width: 30px;
       height: 30px;
       border: 1px solid #ddd;
       border-radius: 0;
       display: inline-block;
       position: absolute;
       right: 0;
       top: 0;
       outline:none;
   }
   .department-search .selected{
       background: lightcyan;
   }
   .modal-footer{
       text-align: center;
   }
	#exp_detail,#exp_detail_app{
		display: table;
	}
	body input[readonly]{
        cursor: pointer;
    }
  .datetimepicker table tr td span.active{
    padding-left: 0;
  }
</style>
<div id="main_search" class="noQueryCust">
	<ul class="channels">
		<c:forEach var="ch" items="${channels}">
			<c:if test="${ch != null}">
			<li class="channelTab" rule="a_siteID_EQ_${siteID}"/>"
				channel="<c:out value="${ch.id}"/>">
				<c:out value="${ch.code}"/>
				稿件
				</li>
			</c:if>
		</c:forEach>
		<li class="channelTab" queryID="3"  channel="0" rule="a_siteID_EQ_${siteID}"/>话题稿件</li>
	</ul>
	<div id="divQueryCust">
		<section id="exp_employeeTab">
			<div id="exp_detail">
					<div class="detail_employee">
						<div id="exp_chTimeRegionDept" class="times">
							<span class="publishTime" style="margin-left: 10px;">订阅时间：</span>
              <a id="allDept" class="time_stat"  href="javascript:setCalender('allDept','')">全部</a>&nbsp;
							<a id="exp_current24HEmp" class="time_stat"  href="javascript:setCalender('current24H','')">24小时内</a>
                            <a id="current7DDept" class="time_stat"  href="javascript:setCalender('current7D','')">最近7天</a>&nbsp;
                            <a id="current14DDept" class="time_stat"  href="javascript:setCalender('current14D','')">最近14天</a>&nbsp;
                            <!-- <a id="current30DDept" class="time_stat"  href="javascript:setCalender('current30D','')">最近30天</a>&nbsp; -->

							<a style="margin-right: 10px;" id="exp_thisMonthEmp" class="time_stat" href="javascript:setCalender('thisMonth','')">本月</a>
							<input id="exp_pubTime_from_emp" class="pubtimeTime" readonly type="text" value="" name="pubTime_from_emp" date-data-format="yyyy-mm-dd hh:ii:ss" /> -
							<input id="exp_pubTime_to_emp" class="pubtimeTime" readonly type="text" value="" name="pubTime_to_emp" date-data-format="yyyy-mm-dd hh:ii:ss"/>
							<!--<input class="lookBtn" style="margin:0px 5px;" type="submit" id="exp_lookMsg" value="查看" />-->
							<img class="lookBtn ml6" src="stat/images/11.png"  id="exp_lookMsg" title="查看" alt="查看" />
							<!--<input class="resetBtn" type="button" id="exp_resetWorkload" value="重置" />-->
							<img class="resetBtn ml6" src="stat/images/12.png"  id="exp_resetWorkload" title="重置" alt="重置" />
							<!--<input class="exportBtn" type="button"  value="导出数据" />-->
						</div>
					</div>
				
			</div>
		</section>


            <input type="hidden" id="siteID" value="${siteID}" /><!-- 站点ID -->
            <form id="form" method="post" style="display: none;"><!-- csv输出 -->
                <input type="hidden" id="jsonData" name="jsonData" />
            </form>

	</div>
</div>
<script type="text/javascript">
	var self_param = {
			docLibID: "<c:out value="${domInfo.docLibID}"/>",
			fvID : "<c:out value="${domInfo.folderID}"/>",
	}
</script>

<script type="text/javascript" src="../e5script/jquery/jquery-1.9.1.min.js"></script>
<!-- <script type="text/javascript" src="../e5script/jquery/jquery.dialog.js"></script>
<script type="text/javascript" src="script/bootstrap-3.3.4/js/bootstrap.min.js"></script> -->
<script type="text/javascript" src="script/bootstrap-datetimepicker/bootstrap-datetimepicker.js" charset="UTF-8"></script>
<script type="text/javascript" src="script/bootstrap-datetimepicker/locales/bootstrap-datetimepicker.zh-CN.js" charset="UTF-8"></script>
<script type="text/javascript" src="../e5script/jquery/jquery-autocomplete/jquery.autocomplete.js"></script>
<script type="text/javascript" src="script/ResourceSelf.js"></script>
<script type="text/javascript" src="script/SearchStatArticles1.js"></script>

<link rel="stylesheet" href="script/bootstrap-3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="script/bootstrap-datetimepicker/css/datetimepicker.css" media="screen">
<link type="text/css" rel="stylesheet" href="../e5script/jquery/dialog.style.css"/>
<link rel="stylesheet" type="text/css" href="../e5script/jquery/jquery-autocomplete/jquery.autocomplete.css"/>


<script type="text/javascript">
         // 页面加载时，部分功能的显示和隐藏

            $("#exp_checkboxId,#exp_checkboxId_app").click(function(){
                //查询
               $("#exp_lookMsg").click();
            })

            //默认选择本月
            $("#allDept").addClass("select_time");
            $("#allDept_app").addClass("select_time");
            setCalender('allDept','');
            setCalender('allDept','_app');
         //时间选择
            $(".time_stat").click(function(){
                $(this).addClass("select_time").siblings().removeClass("select_time");
            });
        //日期控件
            function initDateTimePicker(){
                    $('[id^="exp_pubTime_from_emp"]').datetimepicker({
                        language : 'zh-CN',
                        weekStart : 0,
                        todayBtn : 1,
                        autoclose : true,
                        todayHighlight : true,
                        startView : 2,
                        minView : 0,
                        disabledDaysOfCurrentMonth : 0,
                        forceParse : 0,
                        pickerPosition: "bottom-left",
                        format : 'yyyy-mm-dd hh:ii:00'
                    });

                    $('[id^="exp_pubTime_from_emp"]').datetimepicker().on('changeDate', function(ev) {});

                    $('[id^="exp_pubTime_to_emp"]').datetimepicker({
                        language : 'zh-CN',
                        weekStart : 0,
                        todayBtn : 1,
                        autoclose : true,
                        todayHighlight : true,
                        startView : 2,
                        minView : 0,
                        disabledDaysOfCurrentMonth : 0,
                        forceParse : 0,
                        pickerPosition: "bottom-left",
                        format : 'yyyy-mm-dd hh:ii:00'
                    });

                    $('[id^="exp_pubTime_to_emp"]').datetimepicker().on('changeDate', function(ev) {});
            };

		 	//类似于require.js 的模板加载
			 $.getScript('script/bootstrap-datetimepicker/bootstrap-datetimepicker.js', function() {
				 initDateTimePicker();
			 });

            // 点击上月本月要同时改变日历的值
            function setCalender(type,data) {
                var now = new Date();
                if(type == 'thisMonth'){
                    var ym = now.getFullYear() + "-" + add_zero(now.getMonth() + 1) + "-";
                    $('#exp_pubTime_from_emp' + data).val(ym + "01" + " 00:00:00");
                    $('#exp_pubTime_to_emp' + data).val(ym + add_zero(now.getDate())+ " 23:59:59");

                } else if(type == 'lastMonth'){
                    var year = now.getFullYear();
                    var month = now.getMonth();
                    if(month == 0){
                        year -= 1;
                        month = 12;
                    }
                    var ym = year + "-" + add_zero(month) + "-";
                    $('#exp_pubTime_from_emp' + data).val(ym + "01"+ " 00:00:00");
                    now.setDate(1);
                    now.setMonth(now.getMonth());
                    var cdt = new Date(now.getTime() - 1000 * 60 * 60 * 24);
                    $('#exp_pubTime_to_emp' + data).val(ym + cdt.getDate()+ " 23:59:59");

                } else if(type == 'current24H'){
                    var fromTime = new Date(now.getTime() - 24 * 3600 * 1000);
                    var fromYear = fromTime.getFullYear();
                    var fromMonth = fromTime.getMonth() + 1;
                    if(fromMonth == 0){
                        fromYear -= 1;
                        fromMonth = 12;
                    }
                    fromMonth = add_zero(fromMonth);
                    var fromDay = add_zero(fromTime.getDate());
                    var fromHour = add_zero(fromTime.getHours());
                    var fromMinutes = add_zero(fromTime.getMinutes());
                    var fromSeconds = add_zero(fromTime.getSeconds());
                    var newFromTime = fromYear + '-' + fromMonth + '-' + fromDay + ' ' + fromHour + ':' + fromMinutes + ':' + fromSeconds;
                    $('#exp_pubTime_from_emp' + data).val(newFromTime);
                    var nowTime = new Date(now.getTime());
                    var nowYear = nowTime.getFullYear();
                    var nowMonth = nowTime.getMonth() + 1;
                    if(nowMonth == 0){
                        nowYear -= 1;
                        nowMonth = 12;
                    }
                    nowMonth = add_zero(nowMonth);
                    var nowDay = add_zero(nowTime.getDate());
                    var nowHour = add_zero(nowTime.getHours());
                    var nowMinutes = add_zero(nowTime.getMinutes());
                    var nowSeconds = add_zero(nowTime.getSeconds());
                    var newNowTime = nowYear + '-' + nowMonth + '-' + nowDay + ' ' + nowHour + ':' + nowMinutes + ':' + nowSeconds;
                    $('#exp_pubTime_to_emp' + data).val(newNowTime);

                } else if(type == 'current7D'){
                    var fromTime = new Date(now.getTime() - 7 * 24 * 3600 * 1000);
                                var fromYear = fromTime.getFullYear();
                                var fromMonth = fromTime.getMonth() + 1;
                                if (fromMonth == 0) {
                                    fromYear -= 1;
                                    fromMonth = 12;
                                }
                                fromMonth = add_zero(fromMonth);
                                var fromDay = add_zero(fromTime.getDate());
                                var newFromTime = fromYear + '-' + fromMonth + '-' + fromDay + " 00:00:00";
                                $('#exp_pubTime_from_emp' + data).val(newFromTime);
                                var nowTime = new Date(now.getTime());
                                var nowYear = nowTime.getFullYear();
                                var nowMonth = nowTime.getMonth() + 1;
                                if (nowMonth == 0) {
                                    nowYear -= 1;
                                    nowMonth = 12;
                                }
                                nowMonth = add_zero(nowMonth);
                                var nowDay =add_zero(nowTime.getDate());
                                var newNowTime = nowYear + '-' + nowMonth + '-' + nowDay + " 23:59:59";
                                $('#exp_pubTime_to_emp' + data).val(newNowTime);

                }else if (type == 'current14D') {
                             var fromTime = new Date(now.getTime() - 14 * 24 * 3600 * 1000);
                             var fromYear = fromTime.getFullYear();
                             var fromMonth = fromTime.getMonth() + 1;
                             if (fromMonth == 0) {
                                 fromYear -= 1;
                                 fromMonth = 12;
                             }
                             fromMonth = add_zero(fromMonth);
                             var fromDay = add_zero(fromTime.getDate());
                             var newFromTime = fromYear + '-' + fromMonth + '-' + fromDay + " 00:00:00";
                             $('#exp_pubTime_from_emp' + data).val(newFromTime);
                             var nowTime = new Date(now.getTime());
                             var nowYear = nowTime.getFullYear();
                             var nowMonth = nowTime.getMonth() + 1;
                             if (nowMonth == 0) {
                                 nowYear -= 1;
                                 nowMonth = 12;
                             }
                             nowMonth = add_zero(nowMonth);
                             var nowDay = add_zero(nowTime.getDate());
                             var newNowTime = nowYear + '-' + nowMonth + '-' + nowDay + " 23:59:59";
                             $('#exp_pubTime_to_emp' + data).val(newNowTime);

                         }else if (type == 'current30D') {
                              var fromTime = new Date(now.getTime() - 30 * 24 * 3600 * 1000);
                              var fromYear = fromTime.getFullYear();
                              var fromMonth = fromTime.getMonth() + 1;
                              if (fromMonth == 0) {
                                  fromYear -= 1;
                                  fromMonth = 12;
                              }
                              fromMonth = add_zero(fromMonth);
                              var fromDay =add_zero(fromTime.getDate());
                              var newFromTime = fromYear + '-' + fromMonth + '-' + fromDay + " 00:00:00";
                              $('#exp_pubTime_from_emp' + data).val(newFromTime);
                              var nowTime = new Date(now.getTime());
                              var nowYear = nowTime.getFullYear();
                              var nowMonth = nowTime.getMonth() + 1;
                              if (nowMonth == 0) {
                                  nowYear -= 1;
                                  nowMonth = 12;
                              }
                              nowMonth = add_zero(nowMonth);
                              var nowDay = add_zero(nowTime.getDate());
                              var newNowTime = nowYear + '-' + nowMonth + '-' + nowDay + " 23:59:59";
                              $('#exp_pubTime_to_emp' + data).val(newNowTime);

                          }else if (type == 'allDept') {
                              var fromTime = new Date(now.getTime() - 90 * 365 * 24 * 3600 * 1000);
                              var fromYear = fromTime.getFullYear();
                              var fromMonth = fromTime.getMonth() + 1;
                              if (fromMonth == 0) {
                                  fromYear -= 1;
                                  fromMonth = 12;
                              }
                              fromMonth = add_zero(fromMonth);
                              var fromDay =add_zero(fromTime.getDate());
                              var newFromTime = '1929' + '-' + '01' + '-' + '01' + " 00:00:00";
                              $('#exp_pubTime_from_emp' + data).val(newFromTime);
                              var nowTime = new Date(now.getTime());
                              var nowYear = nowTime.getFullYear();
                              var nowMonth = nowTime.getMonth() + 1;
                              if (nowMonth == 0) {
                                  nowYear -= 1;
                                  nowMonth = 12;
                              }
                              nowMonth = add_zero(nowMonth);
                              var nowDay = add_zero(nowTime.getDate());
                              var newNowTime = nowYear + '-' + nowMonth + '-' + nowDay + " 23:59:59";
                              $('#exp_pubTime_to_emp' + data).val(newNowTime);
                          }

                //查询
                $("#exp_lookMsg").click();
            }
           function add_zero(param){
                   if(param < 10) return "0" + param;
                   return "" + param;
               }


           //打开主栏目选择对话框
          var department_stat={
               colDialog: null,
            colDialogWebApp: null,
            init:function(){
            var type=getQueryString("type");
            if(type!=1 && type!=2){
                $("#exp_column,#exp_column_app").click(department_stat.colSelect);
            }
            },
            colSelect:function(evt){
                   var ch = 1;
                   department_stat.colDialogWebApp = '_app';
                   var channel = $('#main_search li.select').attr('channel');
                   if (channel == 0) {
                       ch = 0;
                       department_stat.colDialogWebApp = '';
                   }
                   var siteID=getQueryString("siteID");
                   var dataUrl = "../xy/column/ColumnCheck.jsp?type=op&siteID=" + siteID + "&ids=" + $("#colID" + department_stat.colDialogWebApp).val() + "&ch=" + ch+"&style=radio&type=all";
                   //var pos = columns_stat._getDialogPos(document.getElementById("colName" + columns_stat.colDialogWebApp));
                   var pos = {left : "350px",top : "50px",width : "1000px",height : "500px"};
                   department_stat.colDialog = e5.dialog({
                       type: "iframe",
                       value: dataUrl
                   }, {
                       showTitle: false,
                       width: "450px",
                       height: "430px",
                       pos: pos,
                       resizable: false
                   });
                   department_stat.colDialog.show();
                 }

          }
           //当用户提交选择的栏目,实现栏目选择树的接口
           function columnClose(filterChecked, allFilterChecked) {
               $("#exp_column" + department_stat.colDialogWebApp).val(allFilterChecked[1]);
               $("#exp_columnID" + department_stat.colDialogWebApp).val(allFilterChecked[0]);
               //查询
               $("#exp_lookMsg").click();
               columnCancel();
           }
           //点取消
           function columnCancel() {
               department_stat.colDialog.close();
           }
            department_stat.init();

           //来源选择
           var department_source = {
            dialog : null,
            init : function() {
                var type=getQueryString("type");
                if(type!=1 && type!=2){
                    $("#exp_srcSelect").click(department_source.select);
                    $("#exp_srcSelect_app").click(department_source.select);
                }
            },
            //来源选择按钮
            select : function(event) {
                var siteID=getQueryString("siteID");
                var url = "../../xy/GroupSelect.do?type=4&siteID=" + siteID;
                //var url = "../../xy/xy/GroupSelect.do?type=4&siteID=" + siteID;
                var pos = {left : "100px",top : "50px",width : "1000px",height : "500px"};
                department_source.dialog = e5.dialog({type : "iframe", value : url}, {
                    showTitle : true,
                    title: "来源选择",
                    width : "1000px",
                    height : "500px",
                    pos : pos,
                    resizable : false
                });
                department_source.dialog.show();
            },

            //选择窗口：选定后
            groupSelectOK: function(docLibID, docID) {
                department_source.dialog.close();

                $.get("../xy/source/findSource.do", {docLibID:docLibID, docID:docID}, function(data){
                       if($("#main_search").children("ul").find(".channelTab").eq(0).hasClass("select")){
                           $("#exp_src").val(data.name);
                           $("#exp_srcID").val(docID)
                       }else{
                           $("#exp_src_app").val(data.name);
                           $("#exp_srcID_app").val(docID)
                       }
                       //查询
                      $("#exp_lookMsg").click();
                });
            },
            //选择窗口：取消后
            groupSelectCancel : function() {
                department_source.dialog.close();
            }
           }
           //回调函数
           function groupSelectOK(docLibID, docID){
                department_source.groupSelectOK(docLibID, docID);
           }

           function groupSelectCancel(){
                department_source.groupSelectCancel();
           }
           department_source.init();

            //人员选择
              var department_select={
                   colDialog: null,
                colDialogWebApp: null,
                init:function(){
                var type=getQueryString("type");
                if(type!=1 && type!=2){
                    $("#exp_editor,#exp_editor_app").click(department_select.colSelect);
                }
                },
                colSelect:function(evt){
                       var ch = 1;
                       department_select.colDialogWebApp = '_app';
                       var channel = $('#main_search li.select').attr('channel');
                       if (channel == 0) {
                           ch = 0;
                           department_select.colDialogWebApp = '';
                       }
                       var siteID=getQueryString("siteID");
                       var dataUrl = "stat/editorSelect.html?type=op&siteID=" + siteID + "&ids=" + $("#colID" + department_select.colDialogWebApp).val() + "&ch=" + ch+"&style=radio&type=all";
                       //var pos = columns_stat._getDialogPos(document.getElementById("colName" + columns_stat.colDialogWebApp));
                       var pos = {left : "340px",top : "40px",width : "1000px",height : "500px"};
                       department_select.colDialog = e5.dialog({
                           type: "iframe",
                           value: dataUrl
                       }, {
                           showTitle: false,
                           width: "600px",
                           height: "462px",
                           pos: pos,
                           resizable: false
                       });
                       department_select.colDialog.show();
                     }

              }
               //点确定
              function selectClose(userName,userId) {
                   $("#exp_editor" + department_select.colDialogWebApp).val(userName);
                   $("#exp_editorID" + department_select.colDialogWebApp).val(userId);
                   //查询
                  $("#exp_lookMsg").click();
                   selectCancel();
               }
               //点取消
               function selectCancel() {
                   department_select.colDialog.close();
               }
                department_select.init();


               	//从url中获取参数值
               function getQueryString(name){
                    var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)");
                    var r = window.location.search.substr(1).match(reg);
                    if(r != null)return unescape(r[2]);
                    return null;
               }
</script>





  
