
<style type="text/css">
	#wrapMain{margin-left:0px; padding: 0;}
	.selfTab{width:70px;cursor:pointer;padding:3px;}
	#searchList,#queryReset{
		background: none;
		margin-top:5px;
		border: none;
	}

	.detail_employee a:focus,.detail_employee a:visited,.detail_employee a:active,.detail_employee a:hover{
		text-decoration: none;
	}

	#exp_detail ._sel,#exp_detail_app ._sel{
		float:left;
		margin:10px 0px 10px 10px;
	}
	._sel .col_sel{
		float:left;
    	width:185px;
	}
	._sel .sel_Id{
		float:left;
    	width:150px;
	}
	._sel .emp_sel{
		float:left;
    	width:240px;
	}
	._sel .src_sel{
		float:left;
    	width:240px;
	}
	._sel .editor_sel{
		float:left;
    	width:240px;
	}
	._sel .articleSelect{
		float:left;
    	width:160px;
	}
	._sel .checkbox_ahthor{
		float:left;
    	width:65px;
	}

	#exp_employeeTab .input_select,#exp_detail .input_selectId,#exp_employeeTab_app .input_select,
	#exp_detail_app .input_selectId{
	    border: 1px solid #ddd;
	    height: 26px;
	    line-height: 26px;
	    padding-left: 5px;
	    color: #333;
	    width: 115px;
	    margin: 0 5px;
		border-radius: 0;
		background:none;
	}
	
	.publishTime{
		color:#666;
    	font-size:13px;
	}
	.publishTime1{
		float:left;
		color:#666;
    	font-size:13px;
    	height:24px;
    	line-height: 24px;
    	margin-right: 5px;
	}
	.articleSelect #exp_articleSelect{
		float:left;
		width:90px;
	    margin-bottom: 0;
	    height: 24px;
	    padding: 0;
	    border-radius: 0;
	    border: 1px solid #A9A9A9;
	    box-shadow: none;
	    cursor: inherit; 
	}
	.articleSelect #exp_articleSelect_app{
		float:left;
		width:90px;
	    margin-bottom: 0;
	    height: 24px;
	    padding: 0;
	    border-radius: 0;
	    border: 1px solid #A9A9A9;
	    box-shadow: none;
	    cursor: inherit; 
	}
    #exp_detail .see,#exp_detail_app .see{
		background: #1bb8fa;
	    color: #fff;
	    border-radius: 3px;
	    border: none;
	    width: 67px;
	    height: 26px;
	}
	
	.detail_employee .lookBtn,.detail_employee .resetBtn{
	   margin-top: -10px;
	}
	.ml6{
		margin-left: 6px;
	}
	#exp_chTimeRegionDept .pubtimeTime,#exp_chTimeRegionDept_app .pubtimeTime{
		border: 1px solid #ddd;
	    height: 26px;
	    font-size: 12px;
	    padding-left: 5px;
	    border-radius: 0;
    	background: #fff;
    	width: 132px;
	}
	.publishTime {
	    color: #666;
	    font-size: 13px;
	    float: left;
	    line-height: 23px;
	}
	#divQueryCust .detail_employee{
	    float:left;
	}
	#divQueryCust_app .detail_employee{
	    float:left;
		clear: both;
	    width:1100px;
	}
	#divQueryCust .detail_employee .times{
	    float:left;
	    clear:both;
	    margin-top: 10px;
	}
	.status{
		border-left: 0;
    	border-right: 0;
    	padding: 10px;
	}
	#doclistframe{
		margin-left: 10px;
	}
	.channels{
		margin-left: 10px;
	}
	#divQueryCust_app .detail_employee .times{
	    float:left;
	    clear:both;
	    margin-top: 6px;
	    margin-left:9px;
	}
	#exp_chTimeRegionDept .time_stat,#exp_chTimeRegionDept_app .time_stat{
	    width: 70px;
	    display: inline-block;
	    text-align: center;
	    color: #333;
	    font-size: 13px;
	    float: left;
	    margin-left: 10px;
	    height: 26px;
	    line-height: 26px;
	    border: 1px solid #ddd;
	    border-radius: 3px;
	}
	.detail_employee .times{
	    float:left;
	    clear:both;
	    margin-top: 10px;
   }
   .page-unselected, .page-selected{
   		height: 22px;
   }
   [class^="icon-"], [class*=" icon-"]{
   		margin-top: 3px;
   }
   #exp_employeeTab .exportBtn{
   		border-radius: 3px;
	    color: #fff;
	    background: #00a0e6;
	    width:93px;
	    height:30px;
	    margin-left:10px;
	    font-size: 13px;
	    cursor: pointer;
	    border: none;
   }
   #exp_employeeTab_app{
        display:none;
   }
   #exp_employeeTab_app .exportBtn{
   		border-radius: 3px;
	    color: #fff;
	    background: #00a0e6;
	    width:93px;
	    height:30px;
	    margin-left:10px;
	    font-size: 13px;
	    cursor: pointer;
	    border: none;
   }
   #exp_detail .input_selectId{
		width: 120px;
   }
   .select_time{
      font-size: 13px;
	  BACKGROUND: #1bb8fa;
	  COLOR: #fff !important;
	  border: none !important;
   }

   .modal .modal-body{
        height: 340px;
    }
   .clearfix:after {
        content: ".";
        display: block;
        clear: both;
        visibility:hidden;
        line-height: 0;
        height: 0;
        font-size:0;
   }
   .fl{
        float: left;
   }
   .department-search{
       margin-left: 160px;
   }
   .department-search input{
       width: 220px;
       height: 30px;
       padding: 0 4px;
       line-height: 30px;
       font-size: 14px;
       font-weight: normal;
       border: 1px solid #ddd;
   }
   .department-search ul{
       border: 1px solid #ddd;
       border-top: none;
       max-height: 280px;
       overflow: auto;
   }
   .department-search ul li{
       height: 30px;
       line-height: 30px;
       text-align: left;
       border-bottom: 1px solid #ddd;
       padding: 4px 0 4px 10px;
       cursor: pointer;
       font-size: 14px;
       font-weight: normal;
       background: none;
   }
   .department-search ul li:nth-last-child(1){
       border-bottom: none;
   }
   .department-search ul li:hover{
       background: lightcyan;
   }
   .modal-body>div{
       position: relative;
   }
   .search-btn{
       width: 30px;
       height: 30px;
       border: 1px solid #ddd;
       border-radius: 0;
       display: inline-block;
       position: absolute;
       right: 0;
       top: 0;
       outline:none;
   }
   .department-search .selected{
       background: lightcyan;
   }
   .modal-footer{
       text-align: center;
   }
	#exp_detail,#exp_detail_app{
		display: table;
	}
	body input[readonly]{
        cursor: pointer;
    }
</style>
<div id="main_search" class="noQueryCust">
	<ul class="channels">
		<li class="channelTab" queryID="2"  channel="0" rule="a_topicID_EQ_${topicID}_AND_b.a_channel_EQ_1">Web稿件</li>
		<li class="channelTab" queryID="3"  channel="1" rule="a_topicID_EQ_${topicID}_AND_b.a_channel_EQ_2">App稿件</li>
	</ul>
	<div id="divQueryCust">
        <input type="hidden" id="channel" value="1" />
	</div>
</div>
<script type="text/javascript">
	var self_param = {
			docLibID: "<c:out value="${domInfo.docLibID}"/>",
			fvID : "<c:out value="${domInfo.folderID}"/>",
	}
</script>
<script type="text/javascript" src="script/ResourceSelf.js"></script>
<script type="text/javascript" src="script/SearchTopicArticle.js"></script>

<script type="text/javascript">
            //切换Tab
            $('li.channelTab').click(function(evt){
                if($(this).attr("channel") == "0"){
                    $("#channel").val("1");
                }else{
                    $("#channel").val("2");
                }
            });
</script>