<div id="main_search">
	<div id="searchBtnArea">
		<table>
			<tr>
				<td>
					<div class="inputTxt"><input type="text" id="queryWord" value="" title="<i18n:message key="workspace.query.quick.hint"/>"/></div>
				</td>
				<td>
					<button class="search" id="btnSearch"></button>
				</td>
				<!-- reset button. hide now
				<td><button class="queryReset" id="queryReset" title="<i18n:message key="workspace.query.reset.hint"/>"></button></td>
				-->
				<td id="btnMoreArea">
					<button class="more" id="btnMore"></button>
				</td>
			</tr>
		</table>
	</div>
	<!-- query -->
	<div id="divQueryCust"></div>
	<!-- filters -->
	<table id="tableFilters">
		<tr>
			<td>
				<select class="slct" name="Filters_0" id="Filters_0" style="display:none"title="<i18n:message key="workspace.status.filter.title"/>"></select>
			</td>
			<td>
				<select class="slct" name="Filters_1" id="Filters_1" style="display:none" title="<i18n:message key="workspace.status.filter.title"/>[2]"></select>
			</td>
			<td>
				<select class="slct" name="Filters_2" id="Filters_2" style="display:none" title="<i18n:message key="workspace.status.filter.title"/>[3]"></select>
			</td>
			<td>
				<select class="slct" name="Filters_3" id="Filters_3" style="display:none" title="<i18n:message key="workspace.status.filter.title"/>[4]"></select>
			</td>
			<td>
				<select class="slct" name="Filters_4" id="Filters_4" style="display:none" title="<i18n:message key="workspace.status.filter.title"/>[5]"></select>
			</td>
			<td>
				<select class="slct" name="Filters_5" id="Filters_5" style="display:none" title="<i18n:message key="workspace.status.filter.title"/>[6]"></select>
			</td>
			<td>
				<select class="slct" name="Filters_6" id="Filters_6" style="display:none" title="<i18n:message key="workspace.status.filter.title"/>[7]"></select>
			</td>
			<td>
				<select class="slct" name="Filters_7" id="Filters_7" style="display:none" title="<i18n:message key="workspace.status.filter.title"/>[8]"></select>
			</td>
			<td>
				<select class="slct" name="Filters_8" id="Filters_8" style="display:none" title="<i18n:message key="workspace.status.filter.title"/>[9]"></select>
			</td>
			<td>
				<select class="slct" name="Filters_9" id="Filters_9" style="display:none" title="<i18n:message key="workspace.status.filter.title"/>[10]"></select>
			</td>
		</tr>
	</table>
</div>
<script type="text/javascript" src="../e5workspace/script/Search.js"></script>